local camera = require("orthographic.camera")

---@class chip
---@field number integer?
---@field current_x integer
---@field current_y integer
---@field number_url url
---@field view hash

---@class field
---@field elements array<array<chip>>
---@field current_i integer
---@field current_j integer?

---@comment
---@param value integer?
local function create_chip()
	local ans = {
		number = value
	}
	return ans
end

---@comment
---@return table
local function create_field()
	local field = {}
	for i = 1, 4, 1 do
		local row = {}
		for j = 1, 4, 1 do
			local chip = create_chip()
			chip.current_i = i
			chip.current_j = j
			table.insert(row, chip)	
		end
		table.insert(field, row)
	end
	return field
end

---@comment
function init()
	local HASH_SQUARE = hash("/square")
	local field = create_field()
	for i, row in ipairs(field) do
		for j, chip in ipairs(row) do
			---@cast chip chip
			local view = collectionfactory.create("factory#square", vmath.vector3())
			chip.current_y = j
			chip.current_x = i
			chip.view = view[HASH_SQUARE]
			chip.number_url = msg.url(nil, chip.view, "number")
			label.set_text(chip.number_url, tostring(chip.current_x) .. tostring(chip.current_y))
			go.set_position(vmath.vector3(chip.current_x, chip.current_y, 0) * 80, chip.view)
		end
	end
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
