local camera = require("orthographic.camera")
local flow = require("flow.flow")
local logic = require("datamodel.logic")

local CHIP_SIZE = 128
local CHIP_SPACING = 8





local game_state = {
	input_left = false,
	input_right = false,
	input_up = false,
	input_down = false,
}


local function create_field_view()
	local HASH_SQUARE = hash("/square")
	local field = logic.create_field()
	logic.init_field(field)

	for i, row in ipairs(field.elements) do
		for j, chip in ipairs(row) do
			if chip then
				---@cast chip chip
				local view = collectionfactory.create("factory#square", vmath.vector3())
				chip.view = view[HASH_SQUARE]
				chip.number_url = msg.url(nil, chip.view, "number")
				if (chip.number ~= 0) then
					label.set_text(chip.number_url, tostring(chip.number))			
				else
					label.set_text(chip.number_url, "")			
				end
			
				go.set_position(vmath.vector3(chip.current_x - 1, chip.current_y - 1, 0) * (CHIP_SIZE + CHIP_SPACING), chip.view)
			end
		end
	end
end

---@comment
---@return direction?
function gameplay_input()
	if game_state.input_left then return "left"
	elseif game_state.input_right then return "right"
	elseif game_state.input_up then return "up"
	elseif game_state.input_down then return "down"
	end
end

---@comment
---@param which direction
local function gameplay_move(which)
	
end

local function gameplay()
	--- spawn and animate
	create_field_view()
	while true do
		flow.delay(0.1)
		local which = gameplay_input()
		if which then
			gameplay_move(which)
		end

		--- process input	
	end
end

---@comment
function init(self)

	math.randomseed(os.time())
	msg.post(".", "acquire_input_focus")
	flow.start(gameplay, nil, nil)
	local v3center = vmath.vector3( -CHIP_SIZE / 2 + (CHIP_SIZE * 4 + CHIP_SPACING * 3) / 2,
	-CHIP_SIZE / 2 + (CHIP_SIZE * 4 + CHIP_SPACING * 3) / 2, 0.0)
	go.set_position(v3center, "/camera")
end

---@diagnostic disable-next-line
function final(self)
	flow.stop()
	msg.post(".", "release_input_focus")
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

---@diagnostic disable-next-line
function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

---@diagnostic disable-next-line
function on_message(self, message_id, message, sender)
	flow.on_message(message_id, message, sender)
end

---@diagnostic disable-next-line
function on_input(self, action_id, action)

	local pressed
	if action.pressed then
		pressed = true
	elseif action.released then
		pressed = false
	else
		return
	end
	
	if action_id == hash("key_left") then
		game_state.input_left = pressed
	elseif action_id == hash("key_right") then
		game_state.input_right = pressed
	elseif action_id == hash("key_up") then
		game_state.input_up = pressed
	elseif action_id == hash("key_down") then
		game_state.input_down = pressed
	end
	
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

---@diagnostic disable-next-line
function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
